### ISSUE TITLE
Service overview shows only greyed out status labels

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1231]
### Current Behavior
* since some time the service section is behaving wrongly and only displayed in grey 

![image](https://github.com/user-attachments/assets/5faea591-e87c-4887-b64f-bbdfbab5005b)

### Expected Behavior

* behavior of the labels of a service should be identical to the behavior of apps. 

### Steps To Reproduce

1. go to https://portal.int.catena-x.net/serviceOverview
2. check the status label of the services

**Comment by manojava-gk** [comment]
@MaximilianHauer recent update(@shahmargi12) in the shared-component's CardChip component expecting smallcase status text. Current behaviour is not changing the server value which is in UPPERCASE to the lowerCase. Similar behaviour is handled in the AppOverview section where the status is explicitly changed to lowerCase. Considering that case, I will update the status in the service card to the lowerCase.

CC - @oyo

**Comment by shahmargi12** [comment]
> @MaximilianHauer recent update(@shahmargi12) in the shared-component's CardChip component expecting smallcase status text. Current behaviour is not changing the server value which is in UPPERCASE to the lowerCase. Similar behaviour is handled in the AppOverview section where the status is explicitly changed to lowerCase. Considering that case, I will update the status in the service card to the lowerCase.
> 
> CC - @oyo

@manojava-gk  I have just removed condition for toLowerCase because the type of status prop defined previously is already in smallCase so if any one pass UPPERCASE value in status prop, then it will show type error where it is used.

export enum StatusVariants {
  release = 'release',
  active = 'active',
  inactive = 'inactive',
  created = 'created',
  inReview = 'in_review',
  enabled = 'enabled',
}

export type Variants =
  | StatusVariants.release
  | StatusVariants.active
  | StatusVariants.inactive
  | StatusVariants.created
  | StatusVariants.inReview
  | StatusVariants.enabled`

**Comment by shahmargi12** [comment]
@MaximilianHauer @manojava-gk 
Updated the code in cardChip component.
PR Link -
https://github.com/eclipse-tractusx/portal-shared-components/pull/351

**Comment by manojava-gk** [comment]
@shahmargi12 thanks for the PR but lets wait for @oyo's input.

**Comment by gopalreddy-bmw** [comment]
Hi @MaximilianHauer 
i tested this issue, it's working fine. Can you close this ticket.

Attached Screenshots for references
![image](https://github.com/user-attachments/assets/9e9a111c-bb29-4583-af34-df0c01f7fc72)
