### ISSUE TITLE
IdP config - Add IdP | Wrong and confusing information on last screen (next steps)

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal-frontend#442]
Detected in version:  **1.8.0-RC2**

### Expected behaviour

Helpful information is shown to the user.

### Current behaviour

Wrong and confusing information is shown to the user:
![image](https://github.com/eclipse-tractusx/portal-frontend/assets/46191613/ea3a9468-659d-4d4b-9333-7be4fdd3aa27)

**Comment by jjeroch** [comment]
Details: the mentioned IdP as well as the mentioned user in the overlay are incorrect. To be rechecked where those data are fetched from. They should show the actual IdP name of the newly activated IdP as well as the user email address of the actual user.

Regarding the bullet point #1 - text update needed since an incorrect information about "Test New IdP Login" is displayed. This button does not exist.

Please reconnect with the designers
