### ISSUE TITLE
App Release process fetch app roles endpoint switch

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#704]
Detected in version *DEV*

After the deletion of obsolete endpoints, the app release process form broke on dev.
The endpoint used for fetching app roles from the backend need to get switched to the newly developed endpoint under https://github.com/eclipse-tractusx/portal-backend/issues/575

**Endpoint**: `/api/AppReleaseProcess/{appID}/roles`
**Method**: `GET``

Optional parameter: languagetag

**Response Body**
```json
[
  {
    "role": "string",
    "descriptions": [
      {
        "languageCode": "string",
        "description": "string"
      }
    ]
  }
]
```

**Comment by jjeroch** [comment]
@lavanya-bmw  https://github.com/eclipse-tractusx/portal-backend/issues/575 is done. You can proceed :)

**Comment by evegufy** [comment]
@lavanya-bmw please see https://github.com/eclipse-tractusx/portal-frontend/issues/736 for additional information about the current behaviour.

**Comment by lavanya-bmw** [comment]
@evegufy addressed https://github.com/eclipse-tractusx/portal-frontend/issues/736 issue 
@julia the endpoint added is '/api/apps/AppReleaseProcess/{appId}/roles' instead of '/api/AppReleaseProcess/{appID}/roles'
Also, the change is tested in validate and publish(step6) and 'in review(app overview)' and is working fine
