### ISSUE TITLE
Company Data Management: trigger v6/sharing-state/ready api post creation of a record

### ISSUE THREAD

**Issue by manojava-gk** [eclipse-tractusx/portal-frontend#955]
Ticket Title:
trigger v6/sharing-state/ready api post creation of a record

Description:
After address/site creation, record is moving to initial state. To start the golden record process it has to move to Ready state. So auto trigger v6/sharing-state/ready api once the record is created.

**Comment by evegufy** [comment]
Hi @nicoprow Mano says this change was discussed with you and @jjeroch.
I'm a bit worried that this change might make sense only if the process is set to manual.
Does this change also make sense if the the business partner data is sent automatically to the golden record process?

This came into my mind because we recently implemented [this change](https://github.com/eclipse-tractusx/portal-backend/issues/845) in the backend in order to respond to the configurability of the process.

cc: @MaximilianHauer

**Comment by evegufy** [comment]
reverted in v2.3.0 with https://github.com/eclipse-tractusx/portal-frontend/pull/1144 because it was decided that BPDM should take care of setting the ready state and needs to be configured accordingly. For this to work, also from portal-backend side the ready state must not be set https://github.com/eclipse-tractusx/portal/pull/445.
